/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as EventsRouteImport } from './routes/events'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubscriptionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/events': typeof EventsRoute
  '/recovery': typeof RecoveryRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/subscriptions/$id': typeof SubscriptionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/events': typeof EventsRoute
  '/recovery': typeof RecoveryRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/subscriptions/$id': typeof SubscriptionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/events': typeof EventsRoute
  '/recovery': typeof RecoveryRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/subscriptions/$id': typeof SubscriptionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/events'
    | '/recovery'
    | '/subscriptions'
    | '/subscriptions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/events'
    | '/recovery'
    | '/subscriptions'
    | '/subscriptions/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/events'
    | '/recovery'
    | '/subscriptions'
    | '/subscriptions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  EventsRoute: typeof EventsRoute
  RecoveryRoute: typeof RecoveryRoute
  SubscriptionsRoute: typeof SubscriptionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/$id': {
      id: '/subscriptions/$id'
      path: '/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
  }
}

interface SubscriptionsRouteChildren {
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
}

const SubscriptionsRouteChildren: SubscriptionsRouteChildren = {
  SubscriptionsIdRoute: SubscriptionsIdRoute,
}

const SubscriptionsRouteWithChildren = SubscriptionsRoute._addFileChildren(
  SubscriptionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  EventsRoute: EventsRoute,
  RecoveryRoute: RecoveryRoute,
  SubscriptionsRoute: SubscriptionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
