/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as CheckoutsRouteImport } from './routes/checkouts'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as BatchesIdRouteImport } from './routes/batches.$id'
import { Route as CheckoutsIdRouteImport } from './routes/checkouts.$id'
import { Route as ReceivablesIdRouteImport } from './routes/receivables.$id'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutsRoute = CheckoutsRouteImport.update({
  id: '/checkouts',
  path: '/checkouts',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIdRoute = BatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BatchesRoute,
} as any)
const CheckoutsIdRoute = CheckoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CheckoutsRoute,
} as any)
const ReceivablesIdRoute = ReceivablesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReceivablesRoute,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubscriptionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/batches': typeof BatchesRouteWithChildren
  '/checkouts': typeof CheckoutsRouteWithChildren
  '/deliveries': typeof DeliveriesRoute
  '/escalations': typeof EscalationsRoute
  '/events': typeof EventsRoute
  '/receivables': typeof ReceivablesRouteWithChildren
  '/recovery': typeof RecoveryRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/batches/$id': typeof BatchesIdRoute
  '/checkouts/$id': typeof CheckoutsIdRoute
  '/receivables/$id': typeof ReceivablesIdRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/batches': typeof BatchesRouteWithChildren
  '/checkouts': typeof CheckoutsRouteWithChildren
  '/deliveries': typeof DeliveriesRoute
  '/escalations': typeof EscalationsRoute
  '/events': typeof EventsRoute
  '/receivables': typeof ReceivablesRouteWithChildren
  '/recovery': typeof RecoveryRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/batches/$id': typeof BatchesIdRoute
  '/checkouts/$id': typeof CheckoutsIdRoute
  '/receivables/$id': typeof ReceivablesIdRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/batches': typeof BatchesRouteWithChildren
  '/checkouts': typeof CheckoutsRouteWithChildren
  '/deliveries': typeof DeliveriesRoute
  '/escalations': typeof EscalationsRoute
  '/events': typeof EventsRoute
  '/receivables': typeof ReceivablesRouteWithChildren
  '/recovery': typeof RecoveryRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/batches/$id': typeof BatchesIdRoute
  '/checkouts/$id': typeof CheckoutsIdRoute
  '/receivables/$id': typeof ReceivablesIdRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/batches'
    | '/checkouts'
    | '/deliveries'
    | '/escalations'
    | '/events'
    | '/receivables'
    | '/recovery'
    | '/subscriptions'
    | '/batches/$id'
    | '/checkouts/$id'
    | '/receivables/$id'
    | '/subscriptions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/batches'
    | '/checkouts'
    | '/deliveries'
    | '/escalations'
    | '/events'
    | '/receivables'
    | '/recovery'
    | '/subscriptions'
    | '/batches/$id'
    | '/checkouts/$id'
    | '/receivables/$id'
    | '/subscriptions/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/batches'
    | '/checkouts'
    | '/deliveries'
    | '/escalations'
    | '/events'
    | '/receivables'
    | '/recovery'
    | '/subscriptions'
    | '/batches/$id'
    | '/checkouts/$id'
    | '/receivables/$id'
    | '/subscriptions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BatchesRoute: typeof BatchesRouteWithChildren
  CheckoutsRoute: typeof CheckoutsRouteWithChildren
  DeliveriesRoute: typeof DeliveriesRoute
  EscalationsRoute: typeof EscalationsRoute
  EventsRoute: typeof EventsRoute
  ReceivablesRoute: typeof ReceivablesRouteWithChildren
  RecoveryRoute: typeof RecoveryRoute
  SubscriptionsRoute: typeof SubscriptionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkouts': {
      id: '/checkouts'
      path: '/checkouts'
      fullPath: '/checkouts'
      preLoaderRoute: typeof CheckoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$id': {
      id: '/batches/$id'
      path: '/$id'
      fullPath: '/batches/$id'
      preLoaderRoute: typeof BatchesIdRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/checkouts/$id': {
      id: '/checkouts/$id'
      path: '/$id'
      fullPath: '/checkouts/$id'
      preLoaderRoute: typeof CheckoutsIdRouteImport
      parentRoute: typeof CheckoutsRoute
    }
    '/receivables/$id': {
      id: '/receivables/$id'
      path: '/$id'
      fullPath: '/receivables/$id'
      preLoaderRoute: typeof ReceivablesIdRouteImport
      parentRoute: typeof ReceivablesRoute
    }
    '/subscriptions/$id': {
      id: '/subscriptions/$id'
      path: '/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
  }
}

interface BatchesRouteChildren {
  BatchesIdRoute: typeof BatchesIdRoute
}

const BatchesRouteChildren: BatchesRouteChildren = {
  BatchesIdRoute: BatchesIdRoute,
}

const BatchesRouteWithChildren =
  BatchesRoute._addFileChildren(BatchesRouteChildren)

interface CheckoutsRouteChildren {
  CheckoutsIdRoute: typeof CheckoutsIdRoute
}

const CheckoutsRouteChildren: CheckoutsRouteChildren = {
  CheckoutsIdRoute: CheckoutsIdRoute,
}

const CheckoutsRouteWithChildren = CheckoutsRoute._addFileChildren(
  CheckoutsRouteChildren,
)

interface ReceivablesRouteChildren {
  ReceivablesIdRoute: typeof ReceivablesIdRoute
}

const ReceivablesRouteChildren: ReceivablesRouteChildren = {
  ReceivablesIdRoute: ReceivablesIdRoute,
}

const ReceivablesRouteWithChildren = ReceivablesRoute._addFileChildren(
  ReceivablesRouteChildren,
)

interface SubscriptionsRouteChildren {
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
}

const SubscriptionsRouteChildren: SubscriptionsRouteChildren = {
  SubscriptionsIdRoute: SubscriptionsIdRoute,
}

const SubscriptionsRouteWithChildren = SubscriptionsRoute._addFileChildren(
  SubscriptionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BatchesRoute: BatchesRouteWithChildren,
  CheckoutsRoute: CheckoutsRouteWithChildren,
  DeliveriesRoute: DeliveriesRoute,
  EscalationsRoute: EscalationsRoute,
  EventsRoute: EventsRoute,
  ReceivablesRoute: ReceivablesRouteWithChildren,
  RecoveryRoute: RecoveryRoute,
  SubscriptionsRoute: SubscriptionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
